version: "3.9"

services:
  credit-app:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: credit-clustering-app

    ports:
      - "8000:8000"

    restart: always

    environment:
      - PYTHONUNBUFFERED=1

    volumes:
      - ./models:/app/models   # ensures model is accessible